// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(starwarsFFI)
import starwarsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_starwars_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_starwars_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureStarwarsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ApiClientProtocol: AnyObject, Sendable {
    
    func fetchFilm(url: String) async throws  -> Film
    
    func fetchFilms(ignoreCache: Bool) async throws  -> [Film]
    
    func fetchPeople(ignoreCache: Bool) async throws  -> [Person]
    
    func fetchPerson(url: String) async throws  -> Person
    
    func fetchPlanet(url: String) async throws  -> Planet
    
    func fetchPlanets(ignoreCache: Bool) async throws  -> [Planet]
    
    func fetchSpecies(url: String) async throws  -> Species
    
    func fetchSpeciesList(ignoreCache: Bool) async throws  -> [Species]
    
    func fetchStarship(url: String) async throws  -> Starship
    
    func fetchStarships(ignoreCache: Bool) async throws  -> [Starship]
    
    func fetchVehicle(url: String) async throws  -> Vehicle
    
    func fetchVehicles(ignoreCache: Bool) async throws  -> [Vehicle]
    
}
open class ApiClient: ApiClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_starwars_fn_clone_apiclient(self.handle, $0) }
    }
public convenience init(httpClient: HttpClient, repository: DataRepository) {
    let handle =
        try! rustCall() {
    uniffi_starwars_fn_constructor_apiclient_new(
        FfiConverterTypeHttpClient_lower(httpClient),
        FfiConverterTypeDataRepository_lower(repository),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_starwars_fn_free_apiclient(handle, $0) }
    }

    

    
open func fetchFilm(url: String)async throws  -> Film  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_film(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFilm_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchFilms(ignoreCache: Bool)async throws  -> [Film]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_films(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFilm.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchPeople(ignoreCache: Bool)async throws  -> [Person]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_people(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypePerson.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchPerson(url: String)async throws  -> Person  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_person(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePerson_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchPlanet(url: String)async throws  -> Planet  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_planet(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePlanet_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchPlanets(ignoreCache: Bool)async throws  -> [Planet]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_planets(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypePlanet.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchSpecies(url: String)async throws  -> Species  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_species(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeSpecies_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchSpeciesList(ignoreCache: Bool)async throws  -> [Species]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_species_list(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeSpecies.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchStarship(url: String)async throws  -> Starship  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_starship(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeStarship_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchStarships(ignoreCache: Bool)async throws  -> [Starship]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_starships(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeStarship.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchVehicle(url: String)async throws  -> Vehicle  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_vehicle(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeVehicle_lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    
open func fetchVehicles(ignoreCache: Bool)async throws  -> [Vehicle]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_apiclient_fetch_vehicles(
                    self.uniffiCloneHandle(),
                    FfiConverterBool.lower(ignoreCache)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeVehicle.lift,
            errorHandler: FfiConverterTypeApiError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApiClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ApiClient

    public static func lift(_ handle: UInt64) throws -> ApiClient {
        return ApiClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ApiClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ApiClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiClient_lift(_ handle: UInt64) throws -> ApiClient {
    return try FfiConverterTypeApiClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiClient_lower(_ value: ApiClient) -> UInt64 {
    return FfiConverterTypeApiClient.lower(value)
}






public protocol DataRepositoryProtocol: AnyObject, Sendable {
    
    func getPlanet(url: String)  -> Planet?
    
    func getPlanets()  -> [Planet]?
    
    func insertPlanet(planet: Planet) 
    
}
open class DataRepository: DataRepositoryProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_starwars_fn_clone_datarepository(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_starwars_fn_constructor_datarepository_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_starwars_fn_free_datarepository(handle, $0) }
    }

    

    
open func getPlanet(url: String) -> Planet?  {
    return try!  FfiConverterOptionTypePlanet.lift(try! rustCall() {
    uniffi_starwars_fn_method_datarepository_get_planet(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func getPlanets() -> [Planet]?  {
    return try!  FfiConverterOptionSequenceTypePlanet.lift(try! rustCall() {
    uniffi_starwars_fn_method_datarepository_get_planets(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insertPlanet(planet: Planet)  {try! rustCall() {
    uniffi_starwars_fn_method_datarepository_insert_planet(
            self.uniffiCloneHandle(),
        FfiConverterTypePlanet_lower(planet),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataRepository: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DataRepository

    public static func lift(_ handle: UInt64) throws -> DataRepository {
        return DataRepository(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DataRepository) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataRepository {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DataRepository, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataRepository_lift(_ handle: UInt64) throws -> DataRepository {
    return try FfiConverterTypeDataRepository.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataRepository_lower(_ value: DataRepository) -> UInt64 {
    return FfiConverterTypeDataRepository.lower(value)
}






public protocol HttpClient: AnyObject, Sendable {
    
    func fetch(url: String) async throws  -> Data
    
}
open class HttpClientImpl: HttpClient, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_starwars_fn_clone_httpclient(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_starwars_fn_free_httpclient(handle, $0) }
    }

    

    
open func fetch(url: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_starwars_fn_method_httpclient_fetch(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_starwars_rust_future_poll_rust_buffer,
            completeFunc: ffi_starwars_rust_future_complete_rust_buffer,
            freeFunc: ffi_starwars_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeNetworkError_lift
        )
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceHttpClient {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceHttpClient] = [UniffiVTableCallbackInterfaceHttpClient(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeHttpClient.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface HttpClient: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeHttpClient.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface HttpClient: handle missing in uniffiClone")
            }
        },
        fetch: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> Data in
                guard let uniffiObj = try? FfiConverterTypeHttpClient.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.fetch(
                     url: try FfiConverterString.lift(url)
                )
            }

            let uniffiHandleSuccess = { (returnValue: Data) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: FfiConverterData.lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeNetworkError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        }
    )]
}

private func uniffiCallbackInitHttpClient() {
    uniffi_starwars_fn_init_callback_vtable_httpclient(UniffiCallbackInterfaceHttpClient.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpClient: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<HttpClient>()

    typealias FfiType = UInt64
    typealias SwiftType = HttpClient

    public static func lift(_ handle: UInt64) throws -> HttpClient {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return HttpClientImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: HttpClient) -> UInt64 {
         if let rustImpl = value as? HttpClientImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HttpClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpClient_lift(_ handle: UInt64) throws -> HttpClient {
    return try FfiConverterTypeHttpClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpClient_lower(_ value: HttpClient) -> UInt64 {
    return FfiConverterTypeHttpClient.lower(value)
}




public struct Film: Equatable, Hashable {
    public let title: String
    public let episodeId: Int32
    public let openingCrawl: String
    public let director: String
    public let producer: String
    public let releaseDate: String
    public let characters: [String]
    public let planets: [String]
    public let starships: [String]
    public let vehicles: [String]
    public let species: [String]
    public let created: String
    public let edited: String
    public let url: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, episodeId: Int32, openingCrawl: String, director: String, producer: String, releaseDate: String, characters: [String], planets: [String], starships: [String], vehicles: [String], species: [String], created: String, edited: String, url: String) {
        self.title = title
        self.episodeId = episodeId
        self.openingCrawl = openingCrawl
        self.director = director
        self.producer = producer
        self.releaseDate = releaseDate
        self.characters = characters
        self.planets = planets
        self.starships = starships
        self.vehicles = vehicles
        self.species = species
        self.created = created
        self.edited = edited
        self.url = url
    }

    

    
}

#if compiler(>=6)
extension Film: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilm: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Film {
        return
            try Film(
                title: FfiConverterString.read(from: &buf), 
                episodeId: FfiConverterInt32.read(from: &buf), 
                openingCrawl: FfiConverterString.read(from: &buf), 
                director: FfiConverterString.read(from: &buf), 
                producer: FfiConverterString.read(from: &buf), 
                releaseDate: FfiConverterString.read(from: &buf), 
                characters: FfiConverterSequenceString.read(from: &buf), 
                planets: FfiConverterSequenceString.read(from: &buf), 
                starships: FfiConverterSequenceString.read(from: &buf), 
                vehicles: FfiConverterSequenceString.read(from: &buf), 
                species: FfiConverterSequenceString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Film, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterInt32.write(value.episodeId, into: &buf)
        FfiConverterString.write(value.openingCrawl, into: &buf)
        FfiConverterString.write(value.director, into: &buf)
        FfiConverterString.write(value.producer, into: &buf)
        FfiConverterString.write(value.releaseDate, into: &buf)
        FfiConverterSequenceString.write(value.characters, into: &buf)
        FfiConverterSequenceString.write(value.planets, into: &buf)
        FfiConverterSequenceString.write(value.starships, into: &buf)
        FfiConverterSequenceString.write(value.vehicles, into: &buf)
        FfiConverterSequenceString.write(value.species, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilm_lift(_ buf: RustBuffer) throws -> Film {
    return try FfiConverterTypeFilm.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilm_lower(_ value: Film) -> RustBuffer {
    return FfiConverterTypeFilm.lower(value)
}


public struct Person: Equatable, Hashable {
    public let birthYear: String
    public let eyeColor: String
    public let films: [String]
    public let gender: String
    public let hairColor: String
    public let height: String
    public let homeworld: String?
    public let mass: String
    public let name: String
    public let skinColor: String
    public let created: String
    public let edited: String
    public let species: [String]
    public let starships: [String]
    public let url: String
    public let vehicles: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(birthYear: String, eyeColor: String, films: [String], gender: String, hairColor: String, height: String, homeworld: String?, mass: String, name: String, skinColor: String, created: String, edited: String, species: [String], starships: [String], url: String, vehicles: [String]) {
        self.birthYear = birthYear
        self.eyeColor = eyeColor
        self.films = films
        self.gender = gender
        self.hairColor = hairColor
        self.height = height
        self.homeworld = homeworld
        self.mass = mass
        self.name = name
        self.skinColor = skinColor
        self.created = created
        self.edited = edited
        self.species = species
        self.starships = starships
        self.url = url
        self.vehicles = vehicles
    }

    

    
}

#if compiler(>=6)
extension Person: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePerson: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Person {
        return
            try Person(
                birthYear: FfiConverterString.read(from: &buf), 
                eyeColor: FfiConverterString.read(from: &buf), 
                films: FfiConverterSequenceString.read(from: &buf), 
                gender: FfiConverterString.read(from: &buf), 
                hairColor: FfiConverterString.read(from: &buf), 
                height: FfiConverterString.read(from: &buf), 
                homeworld: FfiConverterOptionString.read(from: &buf), 
                mass: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                skinColor: FfiConverterString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                species: FfiConverterSequenceString.read(from: &buf), 
                starships: FfiConverterSequenceString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                vehicles: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: Person, into buf: inout [UInt8]) {
        FfiConverterString.write(value.birthYear, into: &buf)
        FfiConverterString.write(value.eyeColor, into: &buf)
        FfiConverterSequenceString.write(value.films, into: &buf)
        FfiConverterString.write(value.gender, into: &buf)
        FfiConverterString.write(value.hairColor, into: &buf)
        FfiConverterString.write(value.height, into: &buf)
        FfiConverterOptionString.write(value.homeworld, into: &buf)
        FfiConverterString.write(value.mass, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.skinColor, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterSequenceString.write(value.species, into: &buf)
        FfiConverterSequenceString.write(value.starships, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterSequenceString.write(value.vehicles, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePerson_lift(_ buf: RustBuffer) throws -> Person {
    return try FfiConverterTypePerson.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePerson_lower(_ value: Person) -> RustBuffer {
    return FfiConverterTypePerson.lower(value)
}


public struct Planet: Equatable, Hashable {
    public let name: String
    public let rotationPeriod: String
    public let orbitalPeriod: String
    public let diameter: String
    public let climate: String
    public let gravity: String
    public let terrain: String
    public let surfaceWater: String
    public let population: String
    public let residents: [String]
    public let films: [String]
    public let created: String
    public let edited: String
    public let url: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, rotationPeriod: String, orbitalPeriod: String, diameter: String, climate: String, gravity: String, terrain: String, surfaceWater: String, population: String, residents: [String], films: [String], created: String, edited: String, url: String) {
        self.name = name
        self.rotationPeriod = rotationPeriod
        self.orbitalPeriod = orbitalPeriod
        self.diameter = diameter
        self.climate = climate
        self.gravity = gravity
        self.terrain = terrain
        self.surfaceWater = surfaceWater
        self.population = population
        self.residents = residents
        self.films = films
        self.created = created
        self.edited = edited
        self.url = url
    }

    

    
}

#if compiler(>=6)
extension Planet: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlanet: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Planet {
        return
            try Planet(
                name: FfiConverterString.read(from: &buf), 
                rotationPeriod: FfiConverterString.read(from: &buf), 
                orbitalPeriod: FfiConverterString.read(from: &buf), 
                diameter: FfiConverterString.read(from: &buf), 
                climate: FfiConverterString.read(from: &buf), 
                gravity: FfiConverterString.read(from: &buf), 
                terrain: FfiConverterString.read(from: &buf), 
                surfaceWater: FfiConverterString.read(from: &buf), 
                population: FfiConverterString.read(from: &buf), 
                residents: FfiConverterSequenceString.read(from: &buf), 
                films: FfiConverterSequenceString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Planet, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.rotationPeriod, into: &buf)
        FfiConverterString.write(value.orbitalPeriod, into: &buf)
        FfiConverterString.write(value.diameter, into: &buf)
        FfiConverterString.write(value.climate, into: &buf)
        FfiConverterString.write(value.gravity, into: &buf)
        FfiConverterString.write(value.terrain, into: &buf)
        FfiConverterString.write(value.surfaceWater, into: &buf)
        FfiConverterString.write(value.population, into: &buf)
        FfiConverterSequenceString.write(value.residents, into: &buf)
        FfiConverterSequenceString.write(value.films, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlanet_lift(_ buf: RustBuffer) throws -> Planet {
    return try FfiConverterTypePlanet.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlanet_lower(_ value: Planet) -> RustBuffer {
    return FfiConverterTypePlanet.lower(value)
}


public struct Species: Equatable, Hashable {
    public let name: String
    public let classification: String
    public let designation: String
    public let averageHeight: String
    public let skinColors: String
    public let hairColors: String
    public let eyeColors: String
    public let averageLifespan: String
    public let homeworld: String?
    public let language: String
    public let people: [String]
    public let films: [String]
    public let created: String
    public let edited: String
    public let url: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, classification: String, designation: String, averageHeight: String, skinColors: String, hairColors: String, eyeColors: String, averageLifespan: String, homeworld: String?, language: String, people: [String], films: [String], created: String, edited: String, url: String) {
        self.name = name
        self.classification = classification
        self.designation = designation
        self.averageHeight = averageHeight
        self.skinColors = skinColors
        self.hairColors = hairColors
        self.eyeColors = eyeColors
        self.averageLifespan = averageLifespan
        self.homeworld = homeworld
        self.language = language
        self.people = people
        self.films = films
        self.created = created
        self.edited = edited
        self.url = url
    }

    

    
}

#if compiler(>=6)
extension Species: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpecies: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Species {
        return
            try Species(
                name: FfiConverterString.read(from: &buf), 
                classification: FfiConverterString.read(from: &buf), 
                designation: FfiConverterString.read(from: &buf), 
                averageHeight: FfiConverterString.read(from: &buf), 
                skinColors: FfiConverterString.read(from: &buf), 
                hairColors: FfiConverterString.read(from: &buf), 
                eyeColors: FfiConverterString.read(from: &buf), 
                averageLifespan: FfiConverterString.read(from: &buf), 
                homeworld: FfiConverterOptionString.read(from: &buf), 
                language: FfiConverterString.read(from: &buf), 
                people: FfiConverterSequenceString.read(from: &buf), 
                films: FfiConverterSequenceString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Species, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.classification, into: &buf)
        FfiConverterString.write(value.designation, into: &buf)
        FfiConverterString.write(value.averageHeight, into: &buf)
        FfiConverterString.write(value.skinColors, into: &buf)
        FfiConverterString.write(value.hairColors, into: &buf)
        FfiConverterString.write(value.eyeColors, into: &buf)
        FfiConverterString.write(value.averageLifespan, into: &buf)
        FfiConverterOptionString.write(value.homeworld, into: &buf)
        FfiConverterString.write(value.language, into: &buf)
        FfiConverterSequenceString.write(value.people, into: &buf)
        FfiConverterSequenceString.write(value.films, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpecies_lift(_ buf: RustBuffer) throws -> Species {
    return try FfiConverterTypeSpecies.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpecies_lower(_ value: Species) -> RustBuffer {
    return FfiConverterTypeSpecies.lower(value)
}


public struct Starship: Equatable, Hashable {
    public let name: String
    public let model: String
    public let manufacturer: String
    public let costInCredits: String
    public let length: String
    public let maxAtmospheringSpeed: String
    public let crew: String
    public let passengers: String
    public let cargoCapacity: String
    public let consumables: String
    public let hyperdriveRating: String
    public let mglt: String
    public let starshipClass: String
    public let pilots: [String]
    public let films: [String]
    public let created: String
    public let edited: String
    public let url: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, model: String, manufacturer: String, costInCredits: String, length: String, maxAtmospheringSpeed: String, crew: String, passengers: String, cargoCapacity: String, consumables: String, hyperdriveRating: String, mglt: String, starshipClass: String, pilots: [String], films: [String], created: String, edited: String, url: String) {
        self.name = name
        self.model = model
        self.manufacturer = manufacturer
        self.costInCredits = costInCredits
        self.length = length
        self.maxAtmospheringSpeed = maxAtmospheringSpeed
        self.crew = crew
        self.passengers = passengers
        self.cargoCapacity = cargoCapacity
        self.consumables = consumables
        self.hyperdriveRating = hyperdriveRating
        self.mglt = mglt
        self.starshipClass = starshipClass
        self.pilots = pilots
        self.films = films
        self.created = created
        self.edited = edited
        self.url = url
    }

    

    
}

#if compiler(>=6)
extension Starship: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStarship: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Starship {
        return
            try Starship(
                name: FfiConverterString.read(from: &buf), 
                model: FfiConverterString.read(from: &buf), 
                manufacturer: FfiConverterString.read(from: &buf), 
                costInCredits: FfiConverterString.read(from: &buf), 
                length: FfiConverterString.read(from: &buf), 
                maxAtmospheringSpeed: FfiConverterString.read(from: &buf), 
                crew: FfiConverterString.read(from: &buf), 
                passengers: FfiConverterString.read(from: &buf), 
                cargoCapacity: FfiConverterString.read(from: &buf), 
                consumables: FfiConverterString.read(from: &buf), 
                hyperdriveRating: FfiConverterString.read(from: &buf), 
                mglt: FfiConverterString.read(from: &buf), 
                starshipClass: FfiConverterString.read(from: &buf), 
                pilots: FfiConverterSequenceString.read(from: &buf), 
                films: FfiConverterSequenceString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Starship, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.model, into: &buf)
        FfiConverterString.write(value.manufacturer, into: &buf)
        FfiConverterString.write(value.costInCredits, into: &buf)
        FfiConverterString.write(value.length, into: &buf)
        FfiConverterString.write(value.maxAtmospheringSpeed, into: &buf)
        FfiConverterString.write(value.crew, into: &buf)
        FfiConverterString.write(value.passengers, into: &buf)
        FfiConverterString.write(value.cargoCapacity, into: &buf)
        FfiConverterString.write(value.consumables, into: &buf)
        FfiConverterString.write(value.hyperdriveRating, into: &buf)
        FfiConverterString.write(value.mglt, into: &buf)
        FfiConverterString.write(value.starshipClass, into: &buf)
        FfiConverterSequenceString.write(value.pilots, into: &buf)
        FfiConverterSequenceString.write(value.films, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStarship_lift(_ buf: RustBuffer) throws -> Starship {
    return try FfiConverterTypeStarship.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStarship_lower(_ value: Starship) -> RustBuffer {
    return FfiConverterTypeStarship.lower(value)
}


public struct Vehicle: Equatable, Hashable {
    public let name: String
    public let model: String
    public let manufacturer: String
    public let costInCredits: String
    public let length: String
    public let maxAtmospheringSpeed: String
    public let crew: String
    public let passengers: String
    public let cargoCapacity: String
    public let consumables: String
    public let vehicleClass: String
    public let pilots: [String]
    public let films: [String]
    public let created: String
    public let edited: String
    public let url: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, model: String, manufacturer: String, costInCredits: String, length: String, maxAtmospheringSpeed: String, crew: String, passengers: String, cargoCapacity: String, consumables: String, vehicleClass: String, pilots: [String], films: [String], created: String, edited: String, url: String) {
        self.name = name
        self.model = model
        self.manufacturer = manufacturer
        self.costInCredits = costInCredits
        self.length = length
        self.maxAtmospheringSpeed = maxAtmospheringSpeed
        self.crew = crew
        self.passengers = passengers
        self.cargoCapacity = cargoCapacity
        self.consumables = consumables
        self.vehicleClass = vehicleClass
        self.pilots = pilots
        self.films = films
        self.created = created
        self.edited = edited
        self.url = url
    }

    

    
}

#if compiler(>=6)
extension Vehicle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVehicle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vehicle {
        return
            try Vehicle(
                name: FfiConverterString.read(from: &buf), 
                model: FfiConverterString.read(from: &buf), 
                manufacturer: FfiConverterString.read(from: &buf), 
                costInCredits: FfiConverterString.read(from: &buf), 
                length: FfiConverterString.read(from: &buf), 
                maxAtmospheringSpeed: FfiConverterString.read(from: &buf), 
                crew: FfiConverterString.read(from: &buf), 
                passengers: FfiConverterString.read(from: &buf), 
                cargoCapacity: FfiConverterString.read(from: &buf), 
                consumables: FfiConverterString.read(from: &buf), 
                vehicleClass: FfiConverterString.read(from: &buf), 
                pilots: FfiConverterSequenceString.read(from: &buf), 
                films: FfiConverterSequenceString.read(from: &buf), 
                created: FfiConverterString.read(from: &buf), 
                edited: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Vehicle, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.model, into: &buf)
        FfiConverterString.write(value.manufacturer, into: &buf)
        FfiConverterString.write(value.costInCredits, into: &buf)
        FfiConverterString.write(value.length, into: &buf)
        FfiConverterString.write(value.maxAtmospheringSpeed, into: &buf)
        FfiConverterString.write(value.crew, into: &buf)
        FfiConverterString.write(value.passengers, into: &buf)
        FfiConverterString.write(value.cargoCapacity, into: &buf)
        FfiConverterString.write(value.consumables, into: &buf)
        FfiConverterString.write(value.vehicleClass, into: &buf)
        FfiConverterSequenceString.write(value.pilots, into: &buf)
        FfiConverterSequenceString.write(value.films, into: &buf)
        FfiConverterString.write(value.created, into: &buf)
        FfiConverterString.write(value.edited, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVehicle_lift(_ buf: RustBuffer) throws -> Vehicle {
    return try FfiConverterTypeVehicle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVehicle_lower(_ value: Vehicle) -> RustBuffer {
    return FfiConverterTypeVehicle.lower(value)
}


public enum ApiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case HttpError(message: String)
    
    case NetworkError(message: String)
    
    case SerializationError(message: String)
    
    case DeserializationError(message: String)
    
    case InvalidResponse(message: String)
    
    case NotFound(message: String)
    
    case Unauthorized(message: String)
    
    case RateLimited(message: String)
    
    case ServerError(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ApiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApiError: FfiConverterRustBuffer {
    typealias SwiftType = ApiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .HttpError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .NetworkError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .SerializationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .DeserializationError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .InvalidResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Unauthorized(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .RateLimited(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .ServerError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ApiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .HttpError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .NetworkError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .SerializationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .DeserializationError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .InvalidResponse(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .NotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Unauthorized(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .RateLimited(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .ServerError(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiError_lift(_ buf: RustBuffer) throws -> ApiError {
    return try FfiConverterTypeApiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiError_lower(_ value: ApiError) -> RustBuffer {
    return FfiConverterTypeApiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Fetchable: Equatable, Hashable {
    
    case planets
    case people
    case films
    case species
    case starships
    case vehicles



public func displayName() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_starwars_fn_method_fetchable_display_name(
            FfiConverterTypeFetchable_lower(self),$0
    )
})
}



}

#if compiler(>=6)
extension Fetchable: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFetchable: FfiConverterRustBuffer {
    typealias SwiftType = Fetchable

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Fetchable {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .planets
        
        case 2: return .people
        
        case 3: return .films
        
        case 4: return .species
        
        case 5: return .starships
        
        case 6: return .vehicles
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Fetchable, into buf: inout [UInt8]) {
        switch value {
        
        
        case .planets:
            writeInt(&buf, Int32(1))
        
        
        case .people:
            writeInt(&buf, Int32(2))
        
        
        case .films:
            writeInt(&buf, Int32(3))
        
        
        case .species:
            writeInt(&buf, Int32(4))
        
        
        case .starships:
            writeInt(&buf, Int32(5))
        
        
        case .vehicles:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFetchable_lift(_ buf: RustBuffer) throws -> Fetchable {
    return try FfiConverterTypeFetchable.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFetchable_lower(_ value: Fetchable) -> RustBuffer {
    return FfiConverterTypeFetchable.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ListItems: Equatable, Hashable {
    
    case planets([String]
    )
    case people([String]
    )
    case films([String]
    )
    case species([String]
    )
    case starships([String]
    )
    case vehicles([String]
    )
    case homeworld(String
    )





}

#if compiler(>=6)
extension ListItems: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListItems: FfiConverterRustBuffer {
    typealias SwiftType = ListItems

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListItems {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .planets(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 2: return .people(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 3: return .films(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 4: return .species(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 5: return .starships(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 6: return .vehicles(try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 7: return .homeworld(try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ListItems, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .planets(v1):
            writeInt(&buf, Int32(1))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .people(v1):
            writeInt(&buf, Int32(2))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .films(v1):
            writeInt(&buf, Int32(3))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .species(v1):
            writeInt(&buf, Int32(4))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .starships(v1):
            writeInt(&buf, Int32(5))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .vehicles(v1):
            writeInt(&buf, Int32(6))
            FfiConverterSequenceString.write(v1, into: &buf)
            
        
        case let .homeworld(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListItems_lift(_ buf: RustBuffer) throws -> ListItems {
    return try FfiConverterTypeListItems.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListItems_lower(_ value: ListItems) -> RustBuffer {
    return FfiConverterTypeListItems.lower(value)
}



public enum NetworkError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case RequestFailed(reason: String
    )
    case Timeout

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension NetworkError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetworkError: FfiConverterRustBuffer {
    typealias SwiftType = NetworkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .RequestFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Timeout

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NetworkError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .RequestFailed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .Timeout:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkError_lift(_ buf: RustBuffer) throws -> NetworkError {
    return try FfiConverterTypeNetworkError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkError_lower(_ value: NetworkError) -> RustBuffer {
    return FfiConverterTypeNetworkError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Selected: Equatable, Hashable {
    
    case film(Film
    )
    case person(Person
    )
    case planet(Planet
    )
    case species(Species
    )
    case starship(Starship
    )
    case vehicle(Vehicle
    )





}

#if compiler(>=6)
extension Selected: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSelected: FfiConverterRustBuffer {
    typealias SwiftType = Selected

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Selected {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .film(try FfiConverterTypeFilm.read(from: &buf)
        )
        
        case 2: return .person(try FfiConverterTypePerson.read(from: &buf)
        )
        
        case 3: return .planet(try FfiConverterTypePlanet.read(from: &buf)
        )
        
        case 4: return .species(try FfiConverterTypeSpecies.read(from: &buf)
        )
        
        case 5: return .starship(try FfiConverterTypeStarship.read(from: &buf)
        )
        
        case 6: return .vehicle(try FfiConverterTypeVehicle.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Selected, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .film(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeFilm.write(v1, into: &buf)
            
        
        case let .person(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypePerson.write(v1, into: &buf)
            
        
        case let .planet(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypePlanet.write(v1, into: &buf)
            
        
        case let .species(v1):
            writeInt(&buf, Int32(4))
            FfiConverterTypeSpecies.write(v1, into: &buf)
            
        
        case let .starship(v1):
            writeInt(&buf, Int32(5))
            FfiConverterTypeStarship.write(v1, into: &buf)
            
        
        case let .vehicle(v1):
            writeInt(&buf, Int32(6))
            FfiConverterTypeVehicle.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelected_lift(_ buf: RustBuffer) throws -> Selected {
    return try FfiConverterTypeSelected.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSelected_lower(_ value: Selected) -> RustBuffer {
    return FfiConverterTypeSelected.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePlanet: FfiConverterRustBuffer {
    typealias SwiftType = Planet?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePlanet.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePlanet.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypePlanet: FfiConverterRustBuffer {
    typealias SwiftType = [Planet]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypePlanet.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypePlanet.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFilm: FfiConverterRustBuffer {
    typealias SwiftType = [Film]

    public static func write(_ value: [Film], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFilm.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Film] {
        let len: Int32 = try readInt(&buf)
        var seq = [Film]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFilm.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePerson: FfiConverterRustBuffer {
    typealias SwiftType = [Person]

    public static func write(_ value: [Person], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePerson.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Person] {
        let len: Int32 = try readInt(&buf)
        var seq = [Person]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePerson.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePlanet: FfiConverterRustBuffer {
    typealias SwiftType = [Planet]

    public static func write(_ value: [Planet], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePlanet.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Planet] {
        let len: Int32 = try readInt(&buf)
        var seq = [Planet]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePlanet.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSpecies: FfiConverterRustBuffer {
    typealias SwiftType = [Species]

    public static func write(_ value: [Species], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSpecies.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Species] {
        let len: Int32 = try readInt(&buf)
        var seq = [Species]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSpecies.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStarship: FfiConverterRustBuffer {
    typealias SwiftType = [Starship]

    public static func write(_ value: [Starship], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStarship.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Starship] {
        let len: Int32 = try readInt(&buf)
        var seq = [Starship]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStarship.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeVehicle: FfiConverterRustBuffer {
    typealias SwiftType = [Vehicle]

    public static func write(_ value: [Vehicle], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeVehicle.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Vehicle] {
        let len: Int32 = try readInt(&buf)
        var seq = [Vehicle]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeVehicle.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFetchable: FfiConverterRustBuffer {
    typealias SwiftType = [Fetchable]

    public static func write(_ value: [Fetchable], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFetchable.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Fetchable] {
        let len: Int32 = try readInt(&buf)
        var seq = [Fetchable]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFetchable.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeListItems: FfiConverterRustBuffer {
    typealias SwiftType = [ListItems]

    public static func write(_ value: [ListItems], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeListItems.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ListItems] {
        let len: Int32 = try readInt(&buf)
        var seq = [ListItems]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeListItems.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureStarwarsInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
private func uniffiTraitInterfaceCallAsync<T>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // Note: it's important we call either `handleSuccess` or `handleError` exactly once.  Each
        // call consumes an Arc reference, which means there should be no possibility of a double
        // call.  The following code is structured so that will will never call both `handleSuccess`
        // and `handleError`, even in the face of weird errors.
        //
        // On platforms that need extra machinery to make C-ABI calls, like JNA or ctypes, it's
        // possible that we fail to make either call.  However, it doesn't seem like this is
        // possible on Swift since swift can just make the C call directly.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

private func uniffiTraitInterfaceCallAsyncWithError<T, E>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    lowerError: @escaping (E) -> RustBuffer,
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // See the note in uniffiTraitInterfaceCallAsync for details on `handleSuccess` and
        // `handleError`.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch let error as E {
            handleError(CALL_ERROR, lowerError(error))
            return
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

// Borrow the callback handle map implementation to store foreign future handles
// TODO: consolidate the handle-map code (https://github.com/mozilla/uniffi-rs/pull/1823)
fileprivate let UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = UniffiHandleMap<UniffiForeignFutureTask>()

// Protocol for tasks that handle foreign futures.
//
// Defining a protocol allows all tasks to be stored in the same handle map.  This can't be done
// with the task object itself, since has generic parameters.
fileprivate protocol UniffiForeignFutureTask {
    func cancel()
}

extension Task: UniffiForeignFutureTask {}

private func uniffiForeignFutureDroppedCallback(handle: UInt64) {
    do {
        let task = try UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle: handle)
        // Set the cancellation flag on the task.  If it's still running, the code can check the
        // cancellation flag or call `Task.checkCancellation()`.  If the task has completed, this is
        // a no-op.
        task.cancel()
    } catch {
        print("uniffiForeignFutureDroppedCallback: handle missing from handlemap")
    }
}

// For testing
public func uniffiForeignFutureHandleCountStarwars() -> Int {
    UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.count
}
public func allFetchable() -> [Fetchable]  {
    return try!  FfiConverterSequenceTypeFetchable.lift(try! rustCall() {
    uniffi_starwars_fn_func_all_fetchable($0
    )
})
}
public func personRelatedItems(person: Person) -> [ListItems]  {
    return try!  FfiConverterSequenceTypeListItems.lift(try! rustCall() {
    uniffi_starwars_fn_func_person_related_items(
        FfiConverterTypePerson_lower(person),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_starwars_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_starwars_checksum_func_all_fetchable() != 46703) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_func_person_related_items() != 10831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_film() != 29515) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_films() != 32635) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_people() != 51794) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_person() != 2190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_planet() != 64974) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_planets() != 51131) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_species() != 60394) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_species_list() != 53838) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_starship() != 23891) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_starships() != 20326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_vehicle() != 14057) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_apiclient_fetch_vehicles() != 18633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_httpclient_fetch() != 26818) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_datarepository_get_planet() != 13100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_datarepository_get_planets() != 37315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_method_datarepository_insert_planet() != 38824) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_constructor_apiclient_new() != 50275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_starwars_checksum_constructor_datarepository_new() != 26238) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitHttpClient()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureStarwarsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all